name: CI

on:
  push:
    branches:
      - '*'

jobs:
  Repositories:
    name: 'Clone Repos'
    runs-on: ubuntu-latest
    steps:
    - name: 'Install SCC'
      run: |
        go install github.com/boyter/scc@latest

    - name: 'Install cloc'
      run: |
        sudo apt install cloc 

    - name: 'clone-repos'
      run: |
        default_dir=/home/runner/work/msc_eng_scripts/msc_eng_scripts
        mkdir -p /home/runner/work/temp/repos
        cd /home/runner/work/temp/repos
        projects=$(ls $default_dir/java-repos-csv/)
        for repo in "${projects[@]}"
        do
          git clone git@github.com:apache/$repo.git
        done

    - name: 'Calculate Lines of Code'
      run: |
        default_dir=/home/runner/work/msc_eng_scripts/msc_eng_scripts
        echo "current directory: $PWD"
        projects=$(ls $default_dir/java-repos-csv/)
        for repo in "${projects[@]}"
        do
          cd $default/temp/repos/$repo
          csv_path=$default_dir/java-repos-csv
          $default_dir/lines_of_code.sh $csv_path $repo
        done

  Coveralls:
    name: 'Coveralls Repositories'
    runs-on: ubuntu-latest
    steps:
    - name: 'Create CSVs'
      run: |
        echo "Coveralls-Api data"

  CodeCov:
    name: 'CodeCov Repositories'
    runs-on: ubuntu-latest
    steps:
    - name: 'Create CSVs'
      run: |
        echo "CodeCov Api data"